[project]
name = "snip-py-core-python"
version = "0.1.0"
description = "Core Python language examples - sequences, dicts, dataclasses, concurrency, etc."
requires-python = ">=3.13"
dependencies = [
    # Minimal dependencies for running Jupyter notebooks
    "ipykernel>=6.29.5",
    "ipython>=9.3.0",
]
